const ingredients = {
  alcool: [
    "GIN",
    "VODKA",
    "RUM",
    "WHISKY",
    "TEQUILA",
    "GRAND MARNIER",
    "COGNAC",
    "CHAMPAGNE",
    "GRAND MARNIER",
    "PASSOA",
  ],
  soft: [
    "TONIC WATER",
    "WATER",
    "PINEAPPLE",
    "PASSION FRUIT JUICE",
    "GINGER BEER",
    "SPRITE",
    "ORANGE",
    "CHERRY",
    "GRENADINE",
    "COCA-COLA",
    "LEMONADE",
    "7-Up",
    "SPRITE",
    "MINT",
  ],
  extra: ["SUGAR", "LIME", "ICE", "LEMON", "MILK", "CACAO"],
};
export default ingredients;
